#!/bin/sh

echo "husky pre-commit: checking formatting..."
if npm run -s format:check; then
  echo "Formatting OK."
  exit 0
fi

echo "Formatting issues found. Running prettier --write ..."
if npm run -s format; then
  # Add any changes produced by formatter
  git add --update
  # Formatting complete, changes staged.
  exit 0
else
  echo "Formatter failed. Aborting commit."
  exit 1
fi
